### ISSUE TITLE
Clarifications on interpretation of style guidelines

### ISSUE THREAD

**Issue by glopesdev** [SainsburyWellcomeCentre/aeon_blog#7]
This issue aims to clarify and interpret the recommendations on [style_and_doc_guidelines.md](https://github.com/SainsburyWellcomeCentre/aeon_blog/blob/main/style_and_doc_guidelines.md). Happy to split into multiple individual issues if it would make resolution easier.

> Code blocks/sections are enclosed in comments that begin and end with <s and /s>, respectively. Nested subsections are used by adding an s for each nesting; e.g., a subsubsection begins and ends with <sss and /sss>, respectively.

Is there a link to what this syntax is referring to, or even just an example of this? I cannot seem to find any example of this anywhere in either our codebase or online in other python code, so we either are not using it at all, or I'm misunderstanding what this guideline is referring to.

> Function names should describe the action they perform. Functions have the following sections in the given order:
>  * One-line summary description, typically as a verb phrase
>  * Long description (optional)
>  * Inputs
>  * Outputs
>  ...

Is there a reference to the names of the docstring sections mentioned in this guideline? I can't seem to find them in [pep8](https://peps.python.org/pep-0008/), [pep257](https://peps.python.org/pep-0257/), or the [numpy's style guide](https://numpydoc.readthedocs.io/en/latest/format.html#sections). The numpy style guide seems to use `Parameters` and `Returns`, which is also the terminology I am most familiar with for function docstrings in other languages (i.e. functions declare parameters and return values).

There also doesn't seem to be any instance of these in our codebase. If we aren't using these names, I would suggest adopting numpydoc as a reference, and updating our style guide accordingly.

> Class names should describe the entity they represent. Classes have the following sections in the given order:
>  * One-line summary description, typically as a noun phrase
>  * Long description (optional)
>  * Examples (optional if included in a separate file)
>  ...

According to the [numpy's style guide](https://numpydoc.readthedocs.io/en/latest/format.html#documenting-classes), classes generally have the exact same sections as functions, except for the `Returns` or `Yields` sections which are not applicable. Instead, they recommend declaring an `Attributes` section describing non-method attributes of the class. This sounds very reasonable, and the use of the term attribute I believe also fits nicely with database terminology (a column in a table is commonly referred to as an attribute too).

Perhaps we could simplify our own style guide for classes pointing to the numpydoc guidance and adopt it for code going forward? Specifically I would remove the duplicated list and simply say that sections are the same as functions, and highlight the few differences, as in numpydoc.

> Docstrings are followed by a blank line before the code begins.

According to [pep257](https://peps.python.org/pep-0257/#multi-line-docstrings) this only applies to classes, and not to functions, so it would be important to clarify.

> Inline comments are written as a short phrase that starts two spaces after the corresponding code.

Could we add to this the very first recommendation regarding inline comments in [pep8](https://peps.python.org/pep-0008/#inline-comments)? "Use inline comments sparingly."

> Classes are in upper Snake_Case (e.g. Alyx_Panel).

This explicitly goes against [pep8](https://peps.python.org/pep-0008/#class-names) that we cite as a reference to our style guide, and also goes against existing naming conventions in numpy, scipy, pandas and the conventions that have been used for DataJoint, so it would be nice to have a bit more clarification on this, ideally with references.

> Prefix 'n' is used for integer values e.g. n_items.
> Suffix 'num' is used for referring to a particular instance e.g. item_num.

Is this some kind of modified Hungarian notation? Why only for integer values? In general I'm not a fan of Hungarian notation in any language, and it doesn't seem to be widely adopted in Python either, but if we do go for it, it's not clear to me why it should be restricted to integer values.

> Suffices that indicate unit measurement are used when using multiple units e.g. wheel_deg and wheel_mm.

While this might make sense in specific cases, I would add a strong recommendation that enforcing units should be used only when absolutely necessary, and that a code review should be performed to verify that using unit-specific parameters is required before accepting code that depends on specific units. Everyone will strongly benefit from keeping our code as unit-independent as possible, especially core reusable code.

> Re-use of variable names (i.e. mutation) is avoided.

Can we clarify what is the meaning of these? Ideally with an example?

> Same variable names across files have the same meanings.

Same as above.

> Complex conditional expressions are avoided; they are replaced with logical variables.

Is this a code style guideline or an implementation guideline? I would keep details of implementation outside of naming and style conventions.

> In function calls, parameters should be specified.

Can we clarify what this means? Is this naming all parameters, including required parameters, e.g. `load(root=root, start=start)`, etc?

**Comment by jkbhagatio** [comment]
Yes, finally some feedback on this :) Let's go over this fully today or sometime this week.

These are general, what I hope to be cross-language/platform guidelines I try to adhere to

**Comment by jkbhagatio** [comment]
Closing this as was agreed upon a few PRs ago
